# Project identifiers
sonar.projectKey=TaskSix
sonar.projectName=TaskSix
sonar.projectVersion=1.0

# Paths
sonar.sources=src
sonar.java.binaries=target/classes

# Connection
sonar.host.url=http://localhost:9000
sonar.login=sqa_0ab1e25f9f02484da2c1f05e8310a22dc187ae99